
export const toolboxElementsEnum = {
    SEND_EMAIL: 'SEND_EMAIL',
    SEND_SMS: 'SEND_SMS',
    ADD_REMOVE_TAG: 'ADD_REMOVE_TAG',
    SUBSCRIBE_LIST: 'SUBSCRIBE_LIST',
    SUBSCRIBE_SEQUENCE: 'SUBSCRIBE_SEQUENCE',
    AUTOMATION: 'AUTOMATION',
    SPLIT: 'SPLIT',
    GO_TO: 'GO_TO',
    WAIT: 'WAIT',
    COMPLETE: 'COMPLETE'
}